version: "3.9"

services:
  web:
    build: ./Frontend/
    container_name: flask_app
    ports:
      - "8080:8080"
    volumes:
      - ./Frontend:/app        
    depends_on:
      - backend

  backend:
    build: ./Backend/
    container_name: fast_api_back
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=tasks_db
      - DB_USER=user
      - DB_PASSWORD=SO.S7

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SO.S7
      MYSQL_DATABASE: tasks_db
      MYSQL_USER: user
      MYSQL_PASSWORD: SO.S7
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  db_data:
