version: "3.9"

services:
  web:
    build: ./Frontend/
    container_name: flask_app
    ports:
      - "8080:8080"
    depends_on:
      - backend
  backend:
    build: ./Backend/
    container_name: fast_api_back
    ports:
      - "8000:8000"
