global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "frontend"
    static_configs:
      - targets: ["web:8080"]

  - job_name: "backend"
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "mysql"
    static_configs:
      - targets: ["db:3306"]
